image: 'ruby:2.5.0'

cache:
  paths:
    - .bundle
    - vendor/
  key: "c7d4616ebb2412a292f06985b1800289"

before_script:
  - gem install bundler --no-ri --no-rdoc
  - RAILS_ENV=test bundle install --path vendor/

stages:
  - mirror

mirror:
  stage: mirror
  script:
    - bin/mirror
  only:
    - master
