image: 'ruby:2.4.3'

cache:
  paths:
    - .bundle
    - vendor/
  key: "3bf4b783174b4fca10b26487f370d2aa"

before_script:
  - gem install bundler --no-ri --no-rdoc
  - RAILS_ENV=test bundle install --path vendor/

stages:
  - mirror

mirror:
  stage: mirror
  script:
    - bin/mirror
  only:
    - master
